site_name: 경영세션 EX 14기
site_description: 한의원 경영세션 EX 14기 아티클 모음집
site_author: 김형규
site_url: https://hani.one
theme: 
  name: material
  language: ko
  font:
    text: 'Noto Sans KR'
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
plugins:
  - search
  - tags
  - privacy
nav:
  - Home: index.md
  - Articles:
    - 경영세션 참여 태도 기준서: articles/session01/경영세션_참여_태도_기준서_v2.0.md
    - 비전, 미션, 대표단계, 사업단계, 팀원 v1.0: articles/session01/비전_미션_대표단계_사업단계_팀원_v1.0.md
    - 대표의 한계를 결정하는 10가지 질문: articles/session01/대표의_한계를_결정하는_10가지_질문.md
    - 한의원 모델을 기획하는 방법 v1.0: articles/session01/한의원_모델을_기획하는_방법_v1.0.md
    - 대표의 문제 해결 사고회로 v1.0: articles/session01/대표의_문제_해결_사고회로_v1.0.md
    - 한의원 브랜딩 하는 법 v1.0: articles/session01/한의원_브랜딩_하는_법_v1.0.md
    - OKR 만들기 가이드라인 v1.0: articles/session01/OKR_만들기_가이드라인_v1.0.md
    - 팀 OKR 회고 하는법 v1.0: articles/session01/팀_OKR_회고_하는법_v1.0.md
    - OKR, 지표관리가 훌륭한 한의원 표본: articles/session01/OKR_지표관리가_훌륭한_한의원_표본.md
    - Forecast Graph를 그리세요: articles/session01/Forecast_Graph를_그리세요.md
    - 원내 커뮤니케이션 가이드라인 v2.0: articles/session01/원내_커뮤니케이션_가이드라인_v2.0.md
    - 한의원 커뮤니케이션 우수케이스: articles/session01/한의원_커뮤니케이션_우수케이스.md
    - 대표를 달라지게 하는 10가지 리프레이밍: articles/session01/대표를_달라지게_하는_10가지_리프레이밍.md
  - Tags:
    - All: tags.md
    - Session 01: tags/session_01.md
    - 참여하는 태도, 비전과 미션을 설정하기: tags/참여하는_태도,_비전과_미션을_설정하기.md
    - 한의원 사업 모델: tags/한의원_사업_모델.md
    - 지표 경영: tags/지표_경영.md
    - 팀 조직력은 어떻게 만드는 걸까?: tags/팀_조직력은_어떻게_만드는_걸까.md
  - Assignments:
    - 총명공진단: assignments/총명공진단.md
    - 총명공진단 세션자료: assignments/총명공진단_세션자료.md
    - 총명공진단 이벤트: assignments/총명공진단_이벤트.md
    - 라인약침: assignments/라인약침.md
    - 비전 미션 가치: assignments/비전미션가치.md
    - 6개월 OKR(2025-07-18): assignments/6개월_OKR(2025-07-18).md
    - 1분 설명서: assignments/1분_설명서.md
    - Forecast Graph(2025-07-18): assignments/Forecast Graph(2025-07-18).md
  - Book Reviews:
    - 왜 일하는가: bookreviews/왜_일하는가.md
  - Tips:
    - 사슬람:
      - (0)주매출 380만원에서 3천만원이 되기까지: tips/saslam/M) 빈의와 부의 사이 (0)주매출 380만원에서 3천만원이 되기까지.md
      - (1)내가 빈의였던 이유: tips/saslam/M) 빈의와 부의 사이 (1)내가 빈의였던 이유.md
    - 경영: tips/경영.md
    - 다이어트: tips/다이어트.md
    - 도대체 뭐라고 하면 한약 드실건가요: tips/도대체-뭐라고-하면-한약-드실건가요.md
    - 한의원을 위한 마케팅 브랜딩 실전 가이드: tips/한의원을_위한_마케팅_브랜딩_실전_가이드.md
    - 다이어트 한약 효과 있는거 맞아요?: tips/다이어트-한약-효과-있는거-맞아요.md
    - 랜딩페이지: tips/landing_page.md

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg